services:
  sglang-router:
    container_name: sglang-router
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./huggingface:/models
      - ./router.ini:/app/router.ini
      - /mnt/data/lmstudio/models/lmstudio-community/Qwen3.6-27B-GGUF:/models2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      - LLAMA_API_KEY=${LLAMA_API_KEY}
    command: >
      --models-preset /app/router.ini
      --models-max 1
      --host 0.0.0.0
      --port 10005
      --flash-attn on
      -b 4096
      -ub 1024
      --context-shift
      --no-warmup



