[Qwopus-27B-Coder-120K-MTP]
model = /models/Jackrong/Qwopus3.6-27B-Coder-MTP-GGUF/Qwopus3.6-27B-Coder-MTP-Q4_K_M.gguf
n-gpu-layers = 99
ctx-size = 120832
cache-type-k = q8_0
cache-type-v = q8_0
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
spec-type = draft-mtp
spec-draft-n-max = 3

[Qwopus-27B-Coder-160K-Vision]
model = /models/Jackrong/Qwopus3.6-27B-Coder-MTP-GGUF/Qwopus3.6-27B-Coder-MTP-Q4_K_M.gguf
mmproj = /models/lmstudio-community/Qwen3.6-27B-GGUF/mmproj-Qwen3.6-27B-BF16.gguf
n-gpu-layers = 99
ctx-size = 161792
cache-type-k = q8_0
cache-type-v = q8_0
# cache-type-k-draft = q8_0
# cache-type-v-draft = q8_0
# spec-type = draft-mtp
# spec-draft-n-max = 3

[SuperGemma-26B-Uncensored]
model = /models/Jackrong/supergemma4-26b-uncensored-gguf-v2/supergemma4-26b-uncensored-fast-v2-Q4_K_M.gguf
chat-template-file = /models/Jackrong/supergemma4-26b-uncensored-gguf-v2/chat_template.copilot.jinja
jinja = true
n-gpu-layers = 99
ctx-size = 65536   # Lowered to prevent a VRAM explosion with f16 ~19GiB with these settings
cache-type-k = f16 # Mandatory for Gemma architecture
cache-type-v = f16 # Mandatory for Gemma architecture
# SERVER-SIDE STOP TOKENS FOR COPILOT
# This tells llama.cpp to force-kill generation the moment the model types these strings
reverse-prompt = "<turn|>"
reverse-prompt = "</s>"
reverse-prompt = "<|turn>user"

[Qwen-27B-Standard]
# Your standard model
model = /models2/Qwen3.6-27B-GGUF/Qwen3.6-27B-Q4_K_M.gguf
ctx-size = 65536
n-gpu-layers = 99
cache-type-k = q8_0
cache-type-v = q8_0
